### ISSUE TITLE
Problem with deprecated axes.color_cycle

### ISSUE THREAD

**Issue by nloira** [ljwolf/wampl#1]
Hi,

I'm trying wes (0.1.3) but got the following error when I added wes to one of my programs:

```
/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
```

I'm trying this on macOS Siera, python 2.7.12, matplotlib 1.5.1.

Thanks,

Nicolás

**Comment by ljwolf** [comment]
Hi, thanks for the issue!

I've just resolved this and made a bugfix release (v. 0.1.4). If you upgrade, the issue should be resolved.
