### ISSUE TITLE
FileNotFoundError when importing wes

### ISSUE THREAD

**Issue by tostenzel** [ljwolf/wampl#4]
After installing wes via pip, when i want to import the package typing `import wes`, I get: 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-e474656cd216> in <module>
----> 1 import wes

~\AppData\Local\conda\conda\envs\uq\lib\site-packages\wes\__init__.py in <module>
----> 1 from ._lib import set_palette, available, plot_palettes, _cycles

~\AppData\Local\conda\conda\envs\uq\lib\site-packages\wes\_lib.py in <module>
      8 datapath = os.path.join(pth, 'colors.json')
      9 
---> 10 _cycles = json.load(open(datapath))
     11 
     12 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Tobias\\AppData\\Local\\conda\\conda\\envs\\uq\\lib\\site-packages\\wes\\colors.json'

Indeed, colors.json is not in this folder.

**Comment by kingaber** [comment]
Same problem.

**Comment by ljwolf** [comment]
Sorry; this should now be resolved with `0.1.5post2`. upgrade the package to resolve.
